---
title       : Practicing with Slidify
subtitle    : Opportunities don't just come, we create them - Unknown
author      : Matthew Owen Dossou
job         : Computational Mathematician
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## HELLO!!!

> 1. Welcome to my short presentation
> 2. I will go through the slides at a slow pace
> 3. Pleae feel free to interrupt me for questions!

--- .class #id 

## This is me in two points

> 1. Tomorrow will be my first birthday
> 2. I already know how to read, solve basic Math problems, and write some computer codes

---
## sharing with you one of my secrets

```{r echo=FALSE, results="asis",message=FALSE}
library(ggplot2)
data(diamonds)
ggplot(diamonds, aes(carat, price))+geom_point(color="cadetblue")
```

---

## Another secret - maybe the last one

```{r echo=FALSE, results="asis",message=FALSE}
library(ggplot2)
data(mtcars)
ggplot(mtcars, aes(disp, mpg)) + geom_point(color="cadetblue") + geom_smooth()
```


